version: '3.9'

services:
  java_app:
    container_name: java_app
    image: pee-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://ueop8w4bdkoea55p:Zto8A76IQgwYEncIF7q9@byhmsxpmqhejxyszxxoj-mysql.services.clever-cloud.com:3306/byhmsxpmqhejxyszxxoj
      - DATABASE_USERNAME=ueop8w4bdkoea55p
      - DATABASE_PASSWORD=Zto8A76IQgwYEncIF7q9
    depends_on:
      - java_db
    command: ["dockerize", "-wait", "tcp://java_db:3306", "-timeout", "30s", "java", "-jar", "/path/to/your/app.jar"]
  java_db:
    container_name: java_db
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Zto8A76IQgwYEncIF7q9
      MYSQL_DATABASE: boliviaxplore
      